include: package:very_good_analysis/analysis_options.5.1.0.yaml
linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
analyzer:
  errors:
    no_adjacent_strings_in_list: ignore
  exclude: 
    - '**/*_generated.dart'
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*_model.dart'
